### ISSUE TITLE
Achievement to offline players ?

### ISSUE THREAD

**Issue by Wotn9** [EddieDover/fvtt-player-achievements#45]
**Is your feature request related to a problem? Please describe.**
I was wondering if this was possible. It was quite a mess with Farchievements as I remember, so if it's too much of a work, maybe just ignore this request.  

**Describe the solution you'd like**
If I could do it directly on my GM account without having a player connected it would make the life easier for me as I got quite a lot of players. (West marches style campaign)

**Describe alternatives you've considered**
Well it can be done if I log on my player account through another browser and give it, but it would be quite a pain in the butt to do it everytime.

**Additional context**
As I said. if it's easy to make, it would be nice, if it's quite a complicated and a mess, just ignore it and i'll continue to use my alternative method.

Thank you for reviewing

**Comment by EddieDover** [comment]
Just so you know, this is something that has come up in casual conversion, and just generally been on my mind since I started work on this module.

Modifying the code so you see all actualized players when they're not online wouldn't be too hard. The problem is how to handle those offline-awarded achievements.

If you just add the achievement to the player and call it a day, then that player never gets a message that they were awarded anything. They would have to be told by the GM or open their achievement list on a whim to discover something new. Moreover, they wouldn't be there for the award at the time everyone else got it, and it might feel a bit empty/meaningless.

Sadly, most people who talk to me are GMs and not Players, so it's difficult to get input from someone on the receiving end.

The only solution I can come up with this would be to have the system store records for achievements awarded to players who aren't online. Then have those 'pending awards' fire off the fanfare at the player's next login and become officially awarded like they normally are. Once you get past the code hurdles, a big factor would be implementing that feature in such a way that it doesn't break anything for people with existing achievement data.

What are your thoughts?

**Comment by Wotn9** [comment]
> If you just add the achievement to the player and call it a day, then that player never gets a message that they were awarded anything. They would have to be told by the GM or open their achievement list on a whim to discover something new. Moreover, they wouldn't be there for the award at the time everyone else got it, and it might feel a bit empty/meaningless.

Aah. Yeah I feel you on that. It would feel empty.

> The only solution I can come up with this would be to have the system store records for achievements awarded to players who aren't online. Then have those 'pending awards' fire off the fanfare at the player's next login and become officially awarded like they normally are. Once you get past the code hurdles, a big factor would be implementing that feature in such a way that it doesn't break anything for people with existing achievement data.

There was as I recall multiples issues about this.
- The fanfare spamming when a character receives multiples achievement when disconnected or when changes browser (because it might be stored in the said cache? )
++ Could use a dialog to "Pass" the unlocked achievement by choice.

- And yeah, the fact taht people could lose their achievement is not really enjoyable either. Maybe having a ... default disabled Setting for it ? Like " Oh you can activate that but back up your achievement before? "
